config/routes.rb
Rails.application.routes.draw do
  
  # get 'toppages/index'

  root "toppages#index"

  resources :tweets, only: [:index, :new, :create, :show] do
    get 'show', to: 'tweets#show'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    @tweets = Tweet.all.order("created_at DESC").limit(9).order('created_at DESC')
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(12)
  end

  def new
    @tweet = Tweet.new
    # @tweet.image.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to root_path
  end

  def show
    @tweet = Tweet.all
    @lat = @tweet
    @lng = @tweet
    gon.lat = @lat
    gon.lng = @lng
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :shop_name, :address, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gourmet
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    %link{rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"}
    = include_gon
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body
    = yield
    %script{src: "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_MAP_KEY"]}&callback=initMap"}
    %script{src: "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
    %script{src: "//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js", type:"text/javascript"}

app/views/toppages/_footer.html.haml
.footer
  .content
    .content__categories
      %h2.content__categories__head カテゴリー
      %ul.content__categories__box
        %li.content__categories__box__into
          = link_to root_path, class: 'content__categories__box__btn' do
            ホーム
        %li.content__categories__box__into
          = link_to tweets_path, class: 'content__categories__box__btn' do
            新着グルメ
        %li.content__categories__box__into
          = link_to new_tweet_path, class: 'content__categories__box__btn' do
            投稿
        %li.content__categories__box__into
          = link_to "#", class: 'content__categories__box__btn' do
            グルメマップ
    .content__sns
      %h2.content__sns__head SNS
      %ul.content__sns__box
        %li.content__sns__box__into
          = link_to "/", class: "content__sns__box__btn" do
            = icon('fab', 'facebook-square',  class: "content__sns__head__btn--icon")
            Facebook
        %li.content__sns__box__into
          = link_to "/", class: "content__sns__box__btn" do
            = icon('fab', 'twitter', class: "content__sns__head__btn--icon")
            Twitter
        %li.content__sns__box__into
          = link_to "/", class: "content__sns__box__btn" do
            = icon('fab', 'instagram', class: "contents__btn--icon")
            Instagram
  .footer__logo
    © GOURMET formUWASA

app/views/toppages/_header-images.html.haml
.box-img
  .box-img__form
    %h2.box-img__form__title グルメコレクション
    .box-img__form__first
      - @tweets.each do |tweet|
        %ul.slider
          %li.slider-item
            = image_tag tweet.image.url, class: 'box-img__form__first__images'

app/views/toppages/_header.html.haml
.main
  .header
    .header__logo
      = link_to root_path, class: "logo" do
        GOURMET
      .header__logo__before
        from.UWASA
    .header__nav
      %ul
        %li.header-nav
          = link_to root_path do
            .menu_title ホーム
            .menu_desc HOME
        %li.header-nav
          = link_to tweets_path do
            .menu_title 新着グルメ
            .menu_desc 　NEWGOURMET
        %li.header-nav
          = link_to new_tweet_path do
            .menu_title  投稿する
            .menu_desc 　TWEET
        %li.header-nav
          = link_to tweet_show_path(:id) do
            .menu_title グルメマップ
            .menu_desc MAP

app/views/toppages/_post.html.haml
.newtopic
  .newtopicHead
    = link_to tweets_path, class: 'newtopicHead__link' do
      %h1.newtopicHead__title
        新着お店情報
  .newtopicBox
    .newtopicBox__lists
      - @tweets.each do |tweet|
        = link_to tweet_show_path(:id), class: 'newtopicBox__lists__link' do
          .newtopicBox__lists__img
            = image_tag tweet.image.url, class: 'newtopicBox__lists__img__imgs'
          .newtopicBox__lists__body
            %h1.newtopicBox__lists__body__shopname
              = tweet.shop_name
            %h1.newtopicBox__lists__body__address
            = tweet.address
  -# = paginate(@tweets)

app/views/toppages/_tweetbtn.html.haml
= link_to new_tweet_path, class: "tweetbtn" do
  .tweetbox
    投稿
  = icon('fas', 'utensils',  class: "tweet-icon")
  

app/views/toppages/index.html.haml
= render "header"
= render "header-images"
= render "post"
= render "footer"
= render "tweetbtn"

app/views/tweets/index.html.haml
= render 'toppages/header'
.tweet-index
  .tweetindexTop
    %h1.tweetindexTop__title
      投稿一覧
  .tweetindexBox
    .tweetindexBox__lists
      - @tweets.each do |tweet|
        = link_to new_tweet_path(tweet), class: 'tweetindexBox__lists__link' do
          .tweetindexBox__lists__img
            = image_tag tweet.image.url, class: 'tweetindexBox__lists__img__imgs'
          .tweetindexBox__lists__body
            %h1.tweetindexBox__lists__body__shopname
            = tweet.shop_name
            %h1.tweetindexBox__lists__body__address
            = tweet.address
  = paginate(@tweets)
= render 'toppages/footer'

app/views/tweets/new.html.haml
= render 'toppages/header'
.tweet-new
  .tweet-new__box
    -# %h1.tweet-new__box__title 投稿
    = form_for @tweet do |f|
      .tweet-new__box__form
        %h3.tweet-new__box__form__image-title 画像投稿
        .tweet-new__box__form__imag-field
          = f.label :image do
            .tweet-new__box__form__imag-field__prev-contents
              - if @tweet.persisted?
                .tweet-new__box__form__imag-field__prev-content
                  = image_tag tweet.image.url, alt: "preview", class: "prev-image"
              - else
                = icon('far', 'image', class: 'tweet-new__box__form__imag-field__icon')
            = f.file_field :image, class: 'tweet-new__box__form__imag-field__upload'
        .tweet-new__box__form__field
          %h3.tweet-new__box__form__field__shop-name お店の名前
          = f.text_field :shop_name, class: 'tweet-new__box__form__field__text-field', placeholder: '例) パティスリーウー'
        .tweet-new__box__form__field
          %h3.tweet-new__box__form__field__address お店の場所
          = f.text_field :address, id: "address", lass: 'tweet-new__box__form__field__text-field', placeholder: '例) 渋谷'
        .tweet-new__box__form__btn
          = f.submit '投稿', onclick: "codeAddress()", class: 'tweet-new__box__form__btn__submit'
= render 'toppages/footer'

app/views/tweets/show.html.haml
= render 'toppages/header'
.show
  .show__maps{id: "map", style: "height: 620px; width: 1400px;"}
= render 'toppages/footer'